### ISSUE TITLE
Wanting to contribute.

### ISSUE THREAD

**Issue by fleventy-5** [sngur/2020-Projects#1]
Hello there sorry for opening this issue since I don't want to spam your mail. I'm looking to contribute to open source to further my skill and I'm doing a principle of  programming  language course in my 2nd year BTech cse So I would like try the khasi programming language implementation .

**Comment by peace-shillong** [comment]
Great, no problem. You can go ahead.

**Comment by peace-shillong** [comment]
Check out the sample code for reference only: 
https://github.com/peace-shillong/KPL

**Comment by peace-shillong** [comment]
> Hello there sorry for opening this issue since I don't want to spam your mail. I'm looking to contribute to open source to further my skill and I'm doing a principle of programming language course in my 2nd year BTech cse So I would like try the khasi programming language implementation .

hope you found what you are looking for.
